[project]
name = "security-dashboard-frontend"
version = "0.1.0"
license = "Apache-2.0"

dependencies = [
  "asfpy[aioldap]",
  # https://github.com/apache/infrastructure-asfquart/pull/107
  "asfquart @ git+https://github.com/raboof/infrastructure-asfquart@oauth-support-client-id-and-secret",
  "hypercorn",
  "pydantic~=2.11",
]

[tool.pytest.ini_options]
norecursedirs = ["notes"]

